@Library('mylibrary')_

pipeline
{
    agent any
    stages
    {
        stage('Download_master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload('maven')
                }
            }
        }
        stage('build_master')
        {
            steps
            {
                script
                {
                    cicd.buildArtifact()
                }
            }
        }
        stage('Deployment_master')
        {
            steps
            {
                script
                {
                    cicd.deployToTomcat('DeclarativePipelineSharedLibrary','172.31.2.4','testapp')
                }
            }
        }
        stage('Testing_master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload('FunctionalTesting')
                    cicd.runSelenium('DeclarativePipelineSharedLibrary')
                }
            }
        }
        stage('Delivery_master')
        {
            steps
            {
                script
                {
                    cicd.deployToTomcat('DeclarativePipelineSharedLibrary','172.31.11.41','prodapp')
                }
            }
        }
    }
}
