@Library('mylibrary')_

pipeline
{
    agent any
    stages
    {
        stage('Download_Loans')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('build_Loans')
        {
            steps
            {
                script
                {
                    cicd.buildArtifact()
                }
            }
        }
     }
}
